#!/bin/sh

if [ "${ENV}" = "local" ]
then cp /etc/hosts docker/hosts
else echo '' > docker/hosts
fi

if ([ "${ENV}" = "local" ] || [ "${ENV}" = "testing" ]) && [ -f docker-compose.yml ]
then dockerfile=""
else dockerfile="-f docker/_base.yml -f docker/${ENV:-production}.yml"
fi

echo "Running in ${ENV:-production} env...";
docker_compose="COMPOSE_HTTP_TIMEOUT=200 ENV=${ENV:-production} docker-compose ${dockerfile}";
eval $docker_compose down --remove-orphans  && eval $docker_compose build && eval $docker_compose up -d
# ENV=${ENV:-production} docker-compose -f docker/_base.yml -f docker/${ENV:-production}.yml up -d --build 
