#!/bin/bash
echo "Running in ${ENV:-production} env...";

if [ "${ENV}" = "local" ] && [ -f docker-compose.yml ]
then dockerfile=""
else dockerfile="-f docker/_base.yml -f docker/${ENV:-production}.yml"
fi

ENV=${ENV:-production} docker-compose ${dockerfile} exec  crm env TERM=xterm bash -l