#!/bin/bash
# ON PRODUCTION ONLY!

echo "Running gulp...";
gulp='/crm/shared/node_modules/gulp/bin/gulp.js'
release_path=`pwd`
COMPOSE_INTERACTIVE_NO_CLI=1 COMPOSE_HTTP_TIMEOUT=500 docker-compose -f ./docker/gulp.yml run -T -w $release_path gulp bash -c "$gulp loyalty; $gulp --production"
