FROM ubuntu

RUN apt-get update

RUN apt-get update

RUN apt-get -y install wget

RUN apt-get -y install gnupg

RUN wget -qO- https://deb.nodesource.com/setup_10.x | bash -

RUN apt-get install -y nodejs

RUN apt-get install -y git

RUN npm install -g gulp
