version: '2'
services:
  crm:
    image: crm
    entrypoint:
      - /crm/current/docker/bin/startup.sh
    ports:
      - "80:8891"
    environment:
      APP_ENV: ${ENV}
    working_dir: /crm/current