version: '2'
services:
  db:
    extends:
      file: "postgres/testing.yml"
      service: db
    networks:
      - giftd-net
    restart: always
  crm:
    build: ./
    volumes:
      - /crm:/crm
      - /root/.composer/cache/:/root/.composer/cache/
      - ~/.ssh:/root/.ssh
    environment:
      APP_ENV: testing
    networks:
      - giftd-net
    restart: always

networks:
  giftd-net:
    driver: bridge