<?php

namespace App\Http\Requests\PublicApi\User;

use App\Http\Requests\BaseFormRequest;
use App\Http\Requests\Traits\UserByEmail;
use App\Http\Requests\Traits\UserByKey;
use App\Http\Requests\Traits\UserByPhone;
use Illuminate\Contracts\Support\MessageBag;

/**
 * Class GiveBonus.
 *
 * @property $auto_create_user
 * @property $email
 * @property $phone
 * @property $user_key
 * @property $name
 * @property $points
 */
class GiveBonus extends BaseFormRequest
{
    use UserByKey;
    use UserByEmail;
    use UserByPhone;

    public function authorize()
    {
        return $this->user()->can('partner');
    }

    public function rules()
    {
        return [
            'email' => 'email',
            'phone' => 'phone',
            'user_key' => 'max:32',
            'name' => 'max:100',
            'points' => 'int|required',
            'auto_create_user' => 'int|in:0,1',
        ];
    }

    public function getBonusReceiver()
    {
        return ($this->getUserByKey() ?: $this->getUserByEmail()) ?: $this->getUserByPhone();
    }

    public function doExtraValidation(MessageBag $messageBag)
    {
        $user = $this->getBonusReceiver();

        if (!$user && !$this->auto_create_user) {
            $messageBag->add('email', 'User not found');
        }

        parent::doExtraValidation($messageBag); // TODO: Change the autogenerated stub
    }
}
